### ISSUE TITLE
Linking error to debug drawings on ubuntu 22.04 when just using vizkit3d_debug_drawings-commands

### ISSUE THREAD

**Issue by haider8645** [dfki-ric/ugv_nav4d#22]
After the changes which use only the `vizkit3d_debug_drawings-commands`, I get a linking error to core V3DD functions.

```
cmake -DENABLE_DEBUG_DRAWINGS=ON -DINSTALL_DEPS=OFF .
make
```

Result:

```
[ 68%] Linking CXX executable ugv_nav4d_bin-qt5
/usr/bin/ld: ../libugv_nav4d.so: undefined reference to `vizkit3dDebugDrawings::DeclaredChannels::getInstance()'
...
```

@chhtz Does simply linking vizkit3d_debug_drawings-commands build for you? Linking against vizkit3d_debug_drawings-qt5 solves the error for me on ubuntu 22.

**Comment by chhtz** [comment]
The `_bin-qt5` should of course link to the actual library, sorry if I messed that up. PR #20 is related (not sure if the ugv_nav4d library should be linked to the V3DD-qt5, though).

**Comment by pierrewillenbrockdfki** [comment]
The main library should not link against V3DD-qt5(or plain V3DD). Please try to avoid that at all cost, there is no way for the tooling to decide if an orogen component is compiled against Qt5 or Qt4 (and deal with it), but if both end up linked(at runtime, dynamically or statically) into the same executable, said executable breaks. This is worse than the C++11 transition, there, at least the c++11 libraries could be linked into non-c++11 executables.

For this reason, V3DD has been split into the GUI-library set and the command-emitter library. The GUI libraries are needed everywhere V3DD primitives are being rendered, but those places already must know which GUI toolkit they are using(because they need to link against that), so they know if they need the Qt4 or Qt5 version of V3DD.
